name: kubuz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29599
title: Studio Kubuz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#e74c3c'
    - '#2980b9'
    - '#ecf0f1'
    - '#9bc9e7'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
