name: kubuz
favicon: null
layout_spectrum: 0.75592
typography_spectrum: 0.29599
title: Studio Kubuz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#44454a'
    - '#161618'
    - '#816b54'
    - '#ba9873'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
