name: kubuz
favicon: null
layout_spectrum: 0.4286021962761879
typography_spectrum: 0.5559233571402729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.14281687582843006
  lightness: 0.9632745212875307
  saturation: 0.8351507217157632
  rhythmicContrast: 0.9120996175333858
purpose: []
